#=========== dein.vim ==========
# vimプラグイン管理

[[plugins]]
repo = 'Shougo/dein.vim'

#========== vim-airline ==========
#画面下部にステータスバーを表示

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
  let g:airline_theme = 'bubblegum'
'''

[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
  let g:airline_powerline_fonts = 1

  " INSERTモードとNORMALモードの切替遅延を無くす
  " https://github.com/bling/vim-airline/wiki/FAQ#there-is-a-pause-when-leaving-insert-mode
  " https://yukidarake.hateblo.jp/entry/2015/07/10/201356
  " set timeout timeoutlen=50
  " <ESC><ESC>で:nohlsearchと競合するため、200に設定
  " <ESC>長押しで:nohlsearch発火
  set timeout timeoutlen=200
'''

#========== nerdtree ==========
#ファイラー

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-n> :NERDTreeToggle<CR>
  " ブックマークを初期表示
  let g:NERDTreeShowBookmarks=1
  " autocmd vimenter * NERDTree
  " Vim起動時にNERDTreeを表示
'''

#========== vim-lsp  ==========
# 各言語の入力支援をLSP経由で受ける
# 事前に $ npm install -g typescript typescript-language-server
# または $ yarn global add typescript typescript-language-server
[[plugins]]
repo = 'prabirshrestha/async.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim', 'asyncomplete.vim', 'asyncomplete-lsp.vim']
hook_add = '''
  " ===== keymaps of vim-lsp =====
  " デフォルトのキーマップ: Ctrl+n で次の候補へ, Ctrl+p で前の候補へ
  nnoremap [lsp]    <Nop>
  nmap     <Space>l [lsp]

  " サーバのstatus ( unknown server/ exited / starting / failed / running / not running )
  nnoremap [lsp]s   :<C-u>LspStatus<CR>
  " Fix format
  nnoremap [lsp]f   :<C-u>LspDocumentFormat<CR>
  " シンボルの情報をhover(ポップアップウィンドウで表示)
  nnoremap [lsp]h   :<C-u>LspHover<CR>
  " referenceを表示
  nnoremap [lsp]r :<C-u>LspReferences<CR>
  " Implementationを表示<CR>
  nnoremap [lsp]i :<C-u>LspImplementation<CR>

  " 定義元へJump
  nnoremap [lsp]j :<C-u>LspDefinition<CR>
  " splitして定義を表示
  nnoremap [lsp]s :<C-u>rightbelow split \| LspDefinition<CR>
  " vsplitして定義を表示
  nnoremap [lsp]v :<C-u>vertical rightbelow split \| LspDefinition<CR>
  " difinitionをポップアップウィンドウで表示
  nnoremap [lsp]d :<C-u>LspPeekDefinition<CR>
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
